repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.290
  hooks:
    - id: ruff
      args: [--fix, --line-length=125]
      stages: [pre-commit]
      # Run the formatter.
    - id: ruff-format
